INSERT INTO `questions` (`id`, `text`, `number`, `event_id`, `created_at`, `updated_at`) VALUES
(1, 'Which World Cup team describes your sex life?', 1, 1, NULL, NULL),
(2, 'What highly infectious disease describes your sex life?', 2, 1, NULL, NULL),
(3, "What's your favorite number?", 3, 1, NULL, NULL),
(4, 'My beliefs hew toward those of the ______ party.', 4, 1, NULL, NULL),
(5, "What's your mobile app of choice?", 5, 1, NULL, NULL),
(6, 'What poem would you recite to your love to prove your ardor and Harvard erudition?', 6, 1, NULL, NULL),
(7, 'Who is your ideal celebrity SO?', 7, 1, NULL, NULL),
(8, 'Who is your ideal fictional SO?', 8, 1, NULL, NULL),
(9, 'Your favorite sport is...', 9, 1, NULL, NULL),
(10, 'What was responsible for your last sleepless night?', 10, 1, NULL, NULL),
(11, 'The John Harvard statue is also called the "statue of three lies." Among those lies is...', 11, 1, NULL, NULL),
(12, 'You meet the love of your life. You...', 12, 1, NULL, NULL),
(13, 'Datamatch is considering a corporate partnership. Would you prefer it to be...', 13, 1, NULL, NULL),
(14, 'Who was the MVP of Super Bowl 49?', 14, 1, NULL, NULL),
(15, 'What is the most desirable trait in an SO?', 15, 1, NULL, NULL),
(16, "Conversely, what's a dealbreaker in an SO?", 16, 1, NULL, NULL),
(17, 'How did your last relationship end?', 17, 1, NULL, NULL),
(18, 'Best way to get a six-pack?', 18, 1, NULL, NULL),
(19, "Because you know I'm all about that...", 19, 1, NULL, NULL),
(20, 'What do you HAVE to do before graduating?', 20, 1, NULL, NULL),
(21, 'What would you do with $350 million?', 21, 1, NULL, NULL),
(22, 'How do you tell them "I love you?"', 22, 1, NULL, NULL),
(23, 'What is love?', 23, 1, NULL, NULL),
(24, 'Crimson headline you expect to see in the near future:', 24, 1, NULL, NULL),
(25, 'First thing to do when you graduate?', 25, 1, NULL, NULL),
(26, 'How would you show off for your potential Valentine?', 26, 1, NULL, NULL),
(27, 'Sexiest pickup line:', 27, 1, NULL, NULL),
(28, 'What did you do during the blizzard?', 28, 1, NULL, NULL),
(29, 'Best place to get a date is...', 29, 1, NULL, NULL),
(30, 'The answer to this question is...', 30, 1, NULL, NULL);

INSERT INTO `answers` (`id`, `text`, `number`, `question_id`, `created_at`, `updated_at`, `types`) VALUES
(1, 'Germany: ruthless and efficient', 1, 1, NULL, NULL, NULL),
(2, 'Brazil: absolutely destroyed', 2, 1, NULL, NULL, NULL),
(3, 'Costa Rica: tiny but formiddable', 3, 1, NULL, NULL, NULL),
(4, 'America: a lot of bravado for a little bit of show', 4, 1, NULL, NULL, NULL),
(5, 'North Korea: not even playing, but you lie about all your wins', 5, 1, NULL, NULL, NULL),
(6, 'Ebola: hot, messy, and causing worldwide panic.', 1, 2, NULL, NULL, NULL),
(7, "Black Plague: I've been inside of everybody in Europe", 2, 2, NULL, NULL, NULL),
(8, 'Influenza: spend all of my time in bed leaking fluids', 3, 2, NULL, NULL, NULL),
(9, 'Chicken pox: I got that out of my system when I was a kid.', 4, 2, NULL, NULL, NULL),
(10, 'Yellow fever.', 5, 2, NULL, NULL, NULL),
(11, '3.1415926535....', 1, 3, NULL, NULL, NULL),
(12, '69', 2, 3, NULL, NULL, NULL),
(13, 'CS50', 3, 3, NULL, NULL, NULL),
(14, '$1.16 billion and counting', 4, 3, NULL, NULL, NULL),
(15, "I don't know. Why don't you give me your number, and we can figure something out?", 5, 3, NULL, NULL, NULL),
(16, 'Democratic', 1, 4, NULL, NULL, NULL),
(17, 'Republican', 2, 4, NULL, NULL, NULL),
(18, 'Sigma Chi', 3, 4, NULL, NULL, NULL),
(19, 'pizza', 4, 4, NULL, NULL, NULL),
(20, 'pset', 5, 4, NULL, NULL, NULL),
(21, 'Tinder: Constantly having sex.', 1, 5, NULL, NULL, NULL),
(22, 'Yik Yak: Bragging about constantly having sex.', 2, 5, NULL, NULL, NULL),
(23, 'Uber: Getting home from constantly having sex.', 3, 5, NULL, NULL, NULL),
(24, 'Vine: Videos of you constantly having sex--full length.', 4, 5, NULL, NULL, NULL),
(25, "Clash of Clans: This is why you're never having sex.", 5, 5, NULL, NULL, NULL),
(26, 'How do I love thee? Let me count the ways. / I love thee to the depth and breadth and GPA', 1, 6, NULL, NULL, NULL),
(27, "Had we but world enough and time / This coyness surely were no crime / But at my back I always hear / Section's winged chariot hurring near", 2, 6, NULL, NULL, NULL),
(28, 'I carry your netflix password with me(i carry it in / my laptop)i am never without it', 3, 6, NULL, NULL, NULL),
(29, 'Come live with me and be my lab partner / And we will all the theorems prove', 4, 6, NULL, NULL, NULL),
(30, "Rose are red / violets are blue / I don't know how to rhyme / Wanna hook up?", 5, 6, NULL, NULL, NULL),
(31, 'Chris Pratt: he can guard my galaxy any day', 1, 7, NULL, NULL, NULL),
(32, 'Amy Poehler: check out those Golden Globes', 2, 7, NULL, NULL, NULL),
(33, 'Kim Jong Un: Glorious Leader is Number One SO.', 3, 7, NULL, NULL, NULL),
(34, 'Dean Khurana: holistically synergize a dynamic relationship-centered infrastructure.', 4, 7, NULL, NULL, NULL),
(35, 'Palmela Handerson: the cousin of Jill.', 5, 7, NULL, NULL, NULL),
(36, 'Cersei Lannister: I love her like a sister.', 1, 8, NULL, NULL, NULL),
(37, "Walter White: I'm absolutely addicted to him.", 2, 8, NULL, NULL, NULL),
(38, 'Smaug the dragon: mature, wealthy, and smolderingly hot.', 3, 8, NULL, NULL, NULL),
(39, "Olaf the snowman: cool as ice and you'll melt his heart.", 4, 8, NULL, NULL, NULL),
(40, 'All my SOs are fictional.', 5, 8, NULL, NULL, NULL),
(41, 'Football', 1, 9, NULL, NULL, NULL),
(42, 'Fantasy football', 2, 9, NULL, NULL, NULL),
(43, 'Beating Yale', 3, 9, NULL, NULL, NULL),
(44, 'Beer pong', 4, 9, NULL, NULL, NULL),
(45, 'Super Smash Bros.', 5, 9, NULL, NULL, NULL),
(46, 'Debugging code :/', 1, 10, NULL, NULL, NULL),
(47, 'The party next door >:|', 2, 10, NULL, NULL, NULL),
(48, 'Netflix adding every season of Friends :D', 3, 10, NULL, NULL, NULL),
(49, 'My professor :(', 4, 10, NULL, NULL, NULL),
(50, 'My professor ;)', 5, 10, NULL, NULL, NULL),
(51, '"Teaching staff will be available to answer all questions."', 1, 11, NULL, NULL, NULL),
(52, '"Of couse I love you."', 2, 11, NULL, NULL, NULL),
(53, '"Living in the Quad isn\'t so bad."', 3, 11, NULL, NULL, NULL),
(54, '"We have your resume, and we\'ll contact you as soon as we can."', 4, 11, NULL, NULL, NULL),
(55, '"I\'m premed because I want to save lives."', 5, 11, NULL, NULL, NULL),
(56, 'Ask them out!', 1, 12, NULL, NULL, NULL),
(57, 'Thank Datamatch.', 2, 12, NULL, NULL, NULL),
(58, 'Swipe right.', 3, 12, NULL, NULL, NULL),
(59, 'Increase the video quality.', 4, 12, NULL, NULL, NULL),
(60, 'Wake up.', 5, 12, NULL, NULL, NULL),
(61, "OK Cupid: we promise we won't run (m)any experiments on you.", 1, 13, NULL, NULL, NULL),
(62, 'Heinz: use condiments', 2, 13, NULL, NULL, NULL),
(63, "Felipe's: love is like a burrito", 3, 13, NULL, NULL, NULL),
(64, "Comcast: a guarantee you'll get screwed.", 4, 13, NULL, NULL, NULL),
(65, 'Harvard DAPA: free water bottle!', 5, 13, NULL, NULL, NULL),
(66, 'Tom Brady.', 1, 14, NULL, NULL, NULL),
(67, "Tom Brady's balls.", 2, 14, NULL, NULL, NULL),
(68, 'Malcolm Butler.', 3, 14, NULL, NULL, NULL),
(69, 'The guy who called a throw instead of a run.', 4, 14, NULL, NULL, NULL),
(70, "Katy Perry's left shark.", 5, 14, NULL, NULL, NULL),
(71, 'High GPA.', 1, 15, NULL, NULL, NULL),
(72, 'Caring, warm, kind...just kidding, ca$h money', 2, 15, NULL, NULL, NULL),
(73, 'Knows how to traverse a red-black tree in O(log n) time.', 3, 15, NULL, NULL, NULL),
(74, 'Knows how to traverse a pair of pants in O(my god) time.', 4, 15, NULL, NULL, NULL),
(75, 'Exists.', 5, 15, NULL, NULL, NULL),
(76, 'Thinks the Kama Sutra is a Harvard dance troupe.', 1, 16, NULL, NULL, NULL),
(77, "When a long list of ex-lovers say s/he's insane. ", 2, 16, NULL, NULL, NULL),
(78, "Doesn't comment code.", 3, 16, NULL, NULL, NULL),
(79, 'Watches Keeping up with the Kardashians.', 4, 16, NULL, NULL, NULL),
(80, 'Lives in the quad.', 5, 16, NULL, NULL, NULL),
(81, 'Unfriended on Facebook.', 1, 17, NULL, NULL, NULL),
(82, 'Deportation.', 2, 17, NULL, NULL, NULL),
(83, 'Apparently naked selfies are "not what I was looking for in a relationship" and "creepy" and "who are you."', 3, 17, NULL, NULL, NULL),
(84, 'Dawn.', 4, 17, NULL, NULL, NULL),
(85, 'Tripped and broke my hand.', 5, 17, NULL, NULL, NULL),
(86, 'Crunches.', 1, 18, NULL, NULL, NULL),
(87, 'Kale burgers.', 2, 18, NULL, NULL, NULL),
(88, 'Zumba', 3, 18, NULL, NULL, NULL),
(89, 'Sharpie.', 4, 18, NULL, NULL, NULL),
(90, 'Fake ID.', 5, 18, NULL, NULL, NULL),
(91, 'Bass.', 1, 19, NULL, NULL, NULL),
(92, 'Electron pair donor.', 2, 19, NULL, NULL, NULL),
(93, 'Means of production by which the superstructure is shaped.', 3, 19, NULL, NULL, NULL),
(94, "I'll show you a base we can get to.", 4, 19, NULL, NULL, NULL),
(95, 'Premed life.', 5, 19, NULL, NULL, NULL),
(96, 'Pee on the statue.', 1, 20, NULL, NULL, NULL),
(97, 'Pee off of Weeks Bridge.', 2, 20, NULL, NULL, NULL),
(98, 'Pee on the stacks.', 3, 20, NULL, NULL, NULL),
(99, 'Pee on Primal Scream.', 4, 20, NULL, NULL, NULL),
(100, 'Pee while having sex during Primal Scream near Weeks Bridge', 5, 20, NULL, NULL, NULL),
(101, 'Rename the School of Public Health.', 1, 21, NULL, NULL, NULL),
(102, 'Buy a private island for me and my Datamatch.', 2, 21, NULL, NULL, NULL),
(103, 'Invest it in bitcoin.', 3, 21, NULL, NULL, NULL),
(104, 'PBR swimming pool.', 4, 21, NULL, NULL, NULL),
(105, 'Pay off my student debt. Well, most of it. ', 5, 21, NULL, NULL, NULL),
(106, 'Ted Mosby. ', 1, 22, NULL, NULL, NULL),
(107, 'Drunk text.', 2, 22, NULL, NULL, NULL),
(108, 'Full page advertisement in the Crimson.', 3, 22, NULL, NULL, NULL),
(109, 'Prolonged twerking.', 4, 22, NULL, NULL, NULL),
(110, '0x49 0x3c 0x33 0x75', 5, 22, NULL, NULL, NULL),
(111, "Baby don't hurt me, don't hurt me.", 1, 23, NULL, NULL, NULL),
(112, 'Spontaneous secretion of nonregular quantities of oxytocin by the posterior pituitary gland.', 2, 23, NULL, NULL, NULL),
(113, "When you finish each other's--sandwiches!", 3, 23, NULL, NULL, NULL),
(114, 'When s/he wakes you up from the hangover in time for class.', 4, 23, NULL, NULL, NULL),
(115, "Kanye's relationship with Kanye.", 5, 23, NULL, NULL, NULL),
(116, '"Professor Donald Pfister Arrested for Underground Mushroom Narcotics Trade."', 1, 24, NULL, NULL, NULL),
(117, '"Eldo Kim Demands Trial By Combat"', 2, 24, NULL, NULL, NULL),
(118, '"Drew Faust Announces New Capital Campaign, Says \'Suck It Stanford\'"', 3, 24, NULL, NULL, NULL),
(119, '"Ec10 Revealed As Not A Real Class: \'Lectures Were Just Reruns of Wheel of Fortune\'"', 4, 24, NULL, NULL, NULL),
(120, '"Entire College Enrolls In CS50"', 5, 24, NULL, NULL, NULL),
(121, 'Sell my soul for money.', 1, 25, NULL, NULL, NULL),
(122, 'Hahaha, "graduate."', 2, 25, NULL, NULL, NULL),
(123, 'Ask my parents if the basement is still empty.', 3, 25, NULL, NULL, NULL),
(124, 'Volunteer for charity--then give up and sell my soul for money.', 4, 25, NULL, NULL, NULL),
(125, 'My TFs.', 5, 25, NULL, NULL, NULL),
(126, 'Ice bucket challenge.', 1, 26, NULL, NULL, NULL),
(127, 'Invade Crimea.', 2, 26, NULL, NULL, NULL),
(128, 'Take a flight out of Malaysia.', 3, 26, NULL, NULL, NULL),
(129, 'Assassinate the leader of North Korea.', 4, 26, NULL, NULL, NULL),
(130, 'Break the Internet.', 5, 26, NULL, NULL, NULL),
(131, "Did it hurt when you fell from heaven? 'Cause your face is pretty messed up.", 1, 27, NULL, NULL, NULL),
(132, 'I want to do to you what the midterms do to the Democrats.', 2, 27, NULL, NULL, NULL),
(133, "Are you Eldo Kim? Because you're the bomb.", 3, 27, NULL, NULL, NULL),
(134, "I'm an endoplasmic reticulum. Would you like me rough or smooth?", 4, 27, NULL, NULL, NULL),
(135, "Hey baby, I'm a level 76 Paladin with dragon armor.", 5, 27, NULL, NULL, NULL),
(136, 'Hit snooze.', 1, 28, NULL, NULL, NULL),
(137, 'Do you want to build a snowman?', 2, 28, NULL, NULL, NULL),
(138, 'Warm up with lots of hot chocolate!', 3, 28, NULL, NULL, NULL),
(139, 'Smuggle in all my cocaine.', 4, 28, NULL, NULL, NULL),
(140, 'Snuggle in all my cocaine.', 5, 28, NULL, NULL, NULL),
(141, 'Datamatch.', 1, 29, NULL, NULL, NULL),
(142, 'The "D"-hall.', 2, 29, NULL, NULL, NULL),
(143, 'The facuty lounge.', 3, 29, NULL, NULL, NULL),
(144, 'The liquor store.', 4, 29, NULL, NULL, NULL),
(145, 'A calendar.', 5, 29, NULL, NULL, NULL),
(146, 'C.', 1, 30, NULL, NULL, NULL),
(147, '42', 2, 30, NULL, NULL, NULL),
(148, 'Bae.', 3, 30, NULL, NULL, NULL),
(149, 'Section kid knows.', 4, 30, NULL, NULL, NULL),
(150, 'The end.', 5, 30, NULL, NULL, NULL);

