INSERT INTO `questions` (`id`, `text`, `number`, `event_id`, `created_at`, `updated_at`) VALUES
(1, 'How do you demonstrate your affection for someone?', 1, 1, NULL, NULL),
(2, 'Which Harvard department best describes your love life?', 2, 1, NULL, NULL),
(3, 'What would be a deal-breaker in a prospective relationship?', 3, 1, NULL, NULL),
(4, 'You : your ideal significant other ::', 4, 1, NULL, NULL),
(5, 'You : your exes ::', 5, 1, NULL, NULL),
(6, 'Where are you on a Thursday night?', 6, 1, NULL, NULL),
(7, 'What did you do during OWAW?', 7, 1, NULL, NULL),
(8, 'You discover that the Maya were right: the world is going to end in 2012. You:', 8, 1, NULL, NULL),
(9, 'What poetic line would you share with your date, to demonstrate both your sensitivity and your Harvard-caliber erudition?', 9, 1, NULL, NULL),
(10, 'What is your most likely secondary concentration?', 10, 1, NULL, NULL),
(11, 'Your last relationship ended:', 11, 1, NULL, NULL),
(12, 'When you take your date out to dinner, what do you wear?', 12, 1, NULL, NULL),
(13, 'What hot new release would you take your date to see?', 13, 1, NULL, NULL),
(14, "There's going to be another snowstorm. Your reaction:", 14, 1, NULL, NULL),
(15, "What's the best animal to use for parenting?", 15, 1, NULL, NULL),
(16, 'Your love life in 2010:', 16, 1, NULL, NULL),
(17, 'Advertising slogan you would least like to see in 2011:', 17, 1, NULL, NULL),
(18, 'If you had a superpower, it would be:', 18, 1, NULL, NULL),
(19, 'You would be most embarrassed if Wikileaks released your:', 19, 1, NULL, NULL),
(20, 'Your email signature:', 20, 1, NULL, NULL),
(21, 'Which character from the Social Network can you best relate to?', 21, 1, NULL, NULL),
(22, 'What punctuation mark best represents your past relationships?', 22, 1, NULL, NULL),
(23, 'What do you drink on your first date?', 23, 1, NULL, NULL),
(24, 'Most enticing proposition:', 24, 1, NULL, NULL),
(25, 'Your desired relationship is most like:', 25, 1, NULL, NULL),
(26, 'You find that you really like two different people at once. How do you solve this problem?', 26, 1, NULL, NULL),
(27, 'What does it mean?', 27, 1, NULL, NULL),
(28, 'When the bed intruder comes, you:', 28, 1, NULL, NULL),
(29, 'How will you check up on your datamatches before contacting them?', 29, 1, NULL, NULL),
(30, 'Why is this question?', 30, 1, NULL, NULL);

INSERT INTO `answers` (`id`, `text`, `number`, `question_id`, `created_at`, `updated_at`, `types`) VALUES
(1, 'Send a thoughtful handwritten letter.', 1, 1, NULL, NULL, NULL),
(2, 'Send completed problem sets for all of his or her courses.', 2, 1, NULL, NULL, NULL),
(3, 'Like all of his or her Facebook activities.', 3, 1, NULL, NULL, NULL),
(4, 'Invade Troy.', 4, 1, NULL, NULL, NULL),
(5, 'Vuvuzela.', 5, 1, NULL, NULL, NULL),
(6, 'Computer Science: At it all night long.', 1, 2, NULL, NULL, NULL),
(7, 'Economics: The more people the better.', 2, 2, NULL, NULL, NULL),
(8, 'Special Concentrations: I make the rules.', 3, 2, NULL, NULL, NULL),
(9, 'Classics: Nothing new in the last thousand years.', 4, 2, NULL, NULL, NULL),
(10, 'East Asian Studies.', 5, 2, NULL, NULL, NULL),
(11, 'Pre-med.', 1, 3, NULL, NULL, NULL),
(12, 'Lives in the quad.', 2, 3, NULL, NULL, NULL),
(13, 'Sings along to Lady Gaga.', 3, 3, NULL, NULL, NULL),
(14, 'Swindled investors out of $20 billion.', 4, 3, NULL, NULL, NULL),
(15, 'Failed the Turing Test.', 5, 3, NULL, NULL, NULL),
(16, 'Brad Pitt : Angelina Jolie', 1, 4, NULL, NULL, NULL),
(17, 'William Shatner : Leonard Nimoy', 2, 4, NULL, NULL, NULL),
(18, 'Glenn Beck : Glenn Beck', 3, 4, NULL, NULL, NULL),
(19, 'CIA : Julian Assange', 4, 4, NULL, NULL, NULL),
(20, 'Richard Feynman : your sister', 5, 4, NULL, NULL, NULL),
(21, 'Bill Clinton : Hillary Clinton', 1, 5, NULL, NULL, NULL),
(22, 'Joe Biden : Sarah Palin', 2, 5, NULL, NULL, NULL),
(23, "Conan O'Brien : Jay Leno", 3, 5, NULL, NULL, NULL),
(24, 'Larry Page : Eric Schmidt', 4, 5, NULL, NULL, NULL),
(25, 'Dave : HAL 9000', 5, 5, NULL, NULL, NULL),
(26, 'In my bed.', 1, 6, NULL, NULL, NULL),
(27, "In someone else's bed.", 2, 6, NULL, NULL, NULL),
(28, 'Doing a problem set.', 3, 6, NULL, NULL, NULL),
(29, "Doing a problem set in someone else's bed.", 4, 6, NULL, NULL, NULL),
(30, 'UHS.', 5, 6, NULL, NULL, NULL),
(31, "Stayed at home where it's warm.", 1, 7, NULL, NULL, NULL),
(32, 'Cured cancer for my thesis.', 2, 7, NULL, NULL, NULL),
(33, 'Filled out a survey about what I did during OWAW.', 3, 7, NULL, NULL, NULL),
(34, 'My TF. (Hey, the term was over...)', 4, 7, NULL, NULL, NULL),
(35, "OWAW. I don't even remember.", 5, 7, NULL, NULL, NULL),
(36, 'Make out with anything that moves.', 1, 8, NULL, NULL, NULL),
(37, "Set your computer's clock back. That usually works, right?", 2, 8, NULL, NULL, NULL),
(38, 'Start selling derivatives.', 3, 8, NULL, NULL, NULL),
(39, 'Dress your infant son in spandex and send him to a strange, distant world in a spaceship made of icicles.', 4, 8, NULL, NULL, NULL),
(40, 'Hit snooze. Several thousand times.', 5, 8, NULL, NULL, NULL),
(41, 'Let me not to the Harvard-marriage of true minds / Admit impediments.', 1, 9, NULL, NULL, NULL),
(42, 'And this maiden she lived with no other thought / Than to love and be loved by me / And also to get an A in orgo.', 2, 9, NULL, NULL, NULL),
(43, 'Who ever loved, that loved not at first sight / At Primal Scream?', 3, 9, NULL, NULL, NULL),
(44, 'Therefore, send not to know / For whom the bell tolls; / It tolls for / Section in seven minutes.', 4, 9, NULL, NULL, NULL),
(45, "Roses are red, / Violets are blue, / Actually I'm kind of just looking for a quick hookup tonight, / How about you?", 5, 9, NULL, NULL, NULL),
(46, 'Sleep Deprivation Studies.', 1, 10, NULL, NULL, NULL),
(47, 'Hangover and Ethanol Biology.', 2, 10, NULL, NULL, NULL),
(48, 'Reality Distortion Field Theory.', 3, 10, NULL, NULL, NULL),
(49, 'Comparative Study of Free Foods.', 4, 10, NULL, NULL, NULL),
(50, 'Defense Against the Dark Arts.', 5, 10, NULL, NULL, NULL),
(51, 'With a bang.', 1, 11, NULL, NULL, NULL),
(52, 'With a tragic Facebook-marriage misunderstanding.', 2, 11, NULL, NULL, NULL),
(53, 'With an SEC investigation.', 3, 11, NULL, NULL, NULL),
(54, 'When you met in person.', 4, 11, NULL, NULL, NULL),
(55, 'The answer cannot be determined from the information given.', 5, 11, NULL, NULL, NULL),
(56, 'Jeans and T-shirt.', 1, 12, NULL, NULL, NULL),
(57, 'Suit and tie.', 2, 12, NULL, NULL, NULL),
(58, 'Birthday suit and tie.', 3, 12, NULL, NULL, NULL),
(59, 'Scrubs and stethoscope.', 4, 12, NULL, NULL, NULL),
(60, 'Robe and wizard hat.', 5, 12, NULL, NULL, NULL),
(61, 'Star Trek XIV: To Boldly Remake Movies Gone Before.', 1, 13, NULL, NULL, NULL),
(62, 'The Social Network Begins: The MySpace Chronicles.', 2, 13, NULL, NULL, NULL),
(63, 'Harry Potter and the Lucrative Franchise: Part 5.', 3, 13, NULL, NULL, NULL),
(64, "Ocean's Forty-Seven.", 4, 13, NULL, NULL, NULL),
(65, 'Rocky &omega;.', 5, 13, NULL, NULL, NULL),
(66, 'Build an igloo.', 1, 14, NULL, NULL, NULL),
(67, 'The more inches the better.', 2, 14, NULL, NULL, NULL),
(68, 'Eh. No snow in the Science Center.', 3, 14, NULL, NULL, NULL),
(69, 'Good thing my room has a fireplace.', 4, 14, NULL, NULL, NULL),
(70, 'OWAW.', 5, 14, NULL, NULL, NULL),
(71, 'Tiger.', 1, 15, NULL, NULL, NULL),
(72, 'Dolphin.', 2, 15, NULL, NULL, NULL),
(73, 'Ostrich.', 3, 15, NULL, NULL, NULL),
(74, 'Crimson.', 4, 15, NULL, NULL, NULL),
(75, 'Firesheep.', 5, 15, NULL, NULL, NULL),
(76, 'Need You Now.', 1, 16, NULL, NULL, NULL),
(77, 'Your Love is My Drug.', 2, 16, NULL, NULL, NULL),
(78, 'Just the Way You Are.', 3, 16, NULL, NULL, NULL),
(79, 'I Just Had Sex.', 4, 16, NULL, NULL, NULL),
(80, 'Telephone.', 5, 16, NULL, NULL, NULL),
(81, 'BP: <s>British Petroleum</s> <s>Beyond Petroleum</s> Blackened Pelicans', 1, 17, NULL, NULL, NULL),
(82, "TSA: It's our business to touch yours.", 2, 17, NULL, NULL, NULL),
(83, 'Google: Introducing SkyNet Cloud Services (Beta).', 3, 17, NULL, NULL, NULL),
(84, 'Apple: We\'ll make "1984" look like 1984.', 4, 17, NULL, NULL, NULL),
(85, 'Facebook: "They trust us. Dumb f—ks."', 5, 17, NULL, NULL, NULL),
(86, 'Flying.', 1, 18, NULL, NULL, NULL),
(87, 'Invisibility.', 2, 18, NULL, NULL, NULL),
(88, 'Python scripting.', 3, 18, NULL, NULL, 'link:http://xkcd.com/353/'),
(89, "Everything on Adam Wheeler's resume.", 4, 18, NULL, NULL, NULL),
(90, 'China.', 5, 18, NULL, NULL, NULL),
(91, 'Diary.', 1, 19, NULL, NULL, NULL),
(92, 'Gmail archive.', 2, 19, NULL, NULL, NULL),
(93, 'Transcript.', 3, 19, NULL, NULL, NULL),
(94, 'Facebook profile.', 4, 19, NULL, NULL, NULL),
(95, 'Inhibitions.', 5, 19, NULL, NULL, NULL),
(96, 'Jonathan Q. Harvard, Degree Candidate in Pretension', 1, 20, NULL, NULL, NULL),
(97, 'jh', 2, 20, NULL, NULL, NULL),
(98, 'j0|-||\\| |-|4r\\/4rD', 3, 20, NULL, NULL, NULL),
(99, 'Sent from my iPhone', 4, 20, NULL, NULL, NULL),
(100, ' ', 5, 20, NULL, NULL, NULL),
(101, "Mark Zuckerburg: I'm CEO, bitch.", 1, 21, NULL, NULL, NULL),
(102, 'Eduardo Saverin: I meet girls in bathroom stalls.', 2, 21, NULL, NULL, NULL),
(103, 'The Winklevii: The harder you grunt, the faster you go.', 3, 21, NULL, NULL, NULL),
(104, "Sean Parker: I'm not unemployed; I'm an entrepreneur.", 4, 21, NULL, NULL, NULL),
(105, 'Christy: I love fire!', 5, 21, NULL, NULL, NULL),
(106, 'Oxford comma: hot, steamy, and erudite.', 1, 22, NULL, NULL, NULL),
(107, 'Em dash: intermittent—breaking up—yet holding together.', 2, 22, NULL, NULL, NULL),
(108, 'Ellipsis: no end in sight...', 3, 22, NULL, NULL, NULL),
(109, 'Semicolon: exotic; misunderstood.', 4, 22, NULL, NULL, NULL),
(110, 'Interrobang: ended suddenly‽', 5, 22, NULL, NULL, NULL),
(111, 'Wine.', 1, 23, NULL, NULL, NULL),
(112, 'Four Loko.', 2, 23, NULL, NULL, NULL),
(113, 'Dining Hall Powerade.', 3, 23, NULL, NULL, NULL),
(114, 'Potion of +10 charisma.', 4, 23, NULL, NULL, NULL),
(115, 'Blood.', 5, 23, NULL, NULL, NULL),
(116, 'Hey, baby, did you know the endowment is on the rise again?', 1, 24, NULL, NULL, NULL),
(117, 'Hey, baby, want to conduct an organic chemistry practicum?', 2, 24, NULL, NULL, NULL),
(118, 'Hey, baby, how about you and I explore some arbitrage opportunities?', 3, 24, NULL, NULL, NULL),
(119, 'Hey, baby, want to come back to my place and opt out of the X-ray scanner?', 4, 24, NULL, NULL, NULL),
(120, 'Like, baby, baby, baby, ohh.', 5, 24, NULL, NULL, 'rickroll:kffacxfA7G4'),
(121, 'Toy Story 3: Playful yet maturing.', 1, 25, NULL, NULL, NULL),
(122, "Inception: You can't tell whether you're dreaming.", 2, 25, NULL, NULL, NULL),
(123, "The Social Network: It's complicated.", 3, 25, NULL, NULL, NULL),
(124, 'Tron: Lots of flair, no substance.', 4, 25, NULL, NULL, NULL),
(125, 'No Strings Attached.', 5, 25, NULL, NULL, NULL),
(126, 'Go out with both of them casually until you get to know them better.', 1, 26, NULL, NULL, NULL),
(127, 'Flip a coin and just go with it.', 2, 26, NULL, NULL, NULL),
(128, 'Wait, since when is a threesome a problem?', 3, 26, NULL, NULL, NULL),
(129, 'Ignore the situation until they both lose interest, thus reducing the problem to a previously considered case.', 4, 26, NULL, NULL, NULL),
(130, 'Wolfram|Alpha.', 5, 26, NULL, NULL, NULL),
(131, 'Double Rainbow.', 1, 27, NULL, NULL, 'rickroll:OQSNhk5ICTI'),
(132, 'Triple Rainbow. ', 2, 27, NULL, NULL, NULL),
(133, 'A million dollars.', 3, 27, NULL, NULL, NULL),
(134, 'A billion dollars.', 4, 27, NULL, NULL, NULL),
(135, 'Lawrence H. Summers.', 5, 27, NULL, NULL, NULL),
(136, 'Hide your kids.', 1, 28, NULL, NULL, NULL),
(137, 'Hide your wife.', 2, 28, NULL, NULL, NULL),
(138, 'Hide your iPhone.', 3, 28, NULL, NULL, NULL),
(139, 'Hide your browser history.', 4, 28, NULL, NULL, NULL),
(140, 'Hide.', 5, 28, NULL, NULL, NULL),
(141, 'Facebook.', 1, 29, NULL, NULL, NULL),
(142, 'Wikileaks.', 2, 29, NULL, NULL, NULL),
(143, 'HUPD reports.', 3, 29, NULL, NULL, NULL),
(144, 'Google Street View.', 4, 29, NULL, NULL, NULL),
(145, '\'); SHOW TABLE Responses --', 5, 29, NULL, NULL, 'link:http://xkcd.com/327/'),
(146, 'Metameta.', 1, 30, NULL, NULL, NULL),
(147, "Ceci n'est pas une question.", 2, 30, NULL, NULL, NULL),
(148, 'Irrelevant. Death of the Author.', 3, 30, NULL, NULL, NULL),
(149, 'See answer (D).', 4, 30, NULL, NULL, NULL),
(150, 'Chuck Norris.', 5, 30, NULL, NULL, NULL);

